### ISSUE TITLE
TypeError: Cannot read property 'hasPermission' of undefined

### ISSUE THREAD

**Issue by isigebengu-mikey** [ZerioDev/Dashboard.io#2]
### English
When visiting my server page after login, I receive 
(http://localhost:3000/servers/<serverid>)
```
TypeError: Cannot read property 'hasPermission' of undefined
    at C:\Users\terry\Downloads\Dashboard.io-master\routes\server.js:11:81
    at Layer.handle [as handle_request] (C:\Users\terry\Downloads\Dashboard.io-master\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\terry\Downloads\Dashboard.io-master\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\terry\Downloads\Dashboard.io-master\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\terry\Downloads\Dashboard.io-master\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\terry\Downloads\Dashboard.io-master\node_modules\express\lib\router\index.js:281:22
    at param (C:\Users\terry\Downloads\Dashboard.io-master\node_modules\express\lib\router\index.js:354:14)
    at param (C:\Users\terry\Downloads\Dashboard.io-master\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (C:\Users\terry\Downloads\Dashboard.io-master\node_modules\express\lib\router\index.js:410:3)
    at next (C:\Users\terry\Downloads\Dashboard.io-master\node_modules\express\lib\router\index.js:275:10)
```
### French
Lors de la visite de ma page serveur après la connexion, je reçois
(http://localhost:3000/servers/<serverid>)
```
TypeError: Cannot read property 'hasPermission' of undefined
    at C:\Users\terry\Downloads\Dashboard.io-master\routes\server.js:11:81
    at Layer.handle [as handle_request] (C:\Users\terry\Downloads\Dashboard.io-master\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\terry\Downloads\Dashboard.io-master\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\terry\Downloads\Dashboard.io-master\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\terry\Downloads\Dashboard.io-master\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\terry\Downloads\Dashboard.io-master\node_modules\express\lib\router\index.js:281:22
    at param (C:\Users\terry\Downloads\Dashboard.io-master\node_modules\express\lib\router\index.js:354:14)
    at param (C:\Users\terry\Downloads\Dashboard.io-master\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (C:\Users\terry\Downloads\Dashboard.io-master\node_modules\express\lib\router\index.js:410:3)
    at next (C:\Users\terry\Downloads\Dashboard.io-master\node_modules\express\lib\router\index.js:275:10)
```
![image](https://user-images.githubusercontent.com/73202594/97903465-12ac6380-1d0d-11eb-91c1-e30540bf3c30.png)

**Comment by ZerioDev** [comment]
Hello, what version of discord.js do you use ?

**Comment by isigebengu-mikey** [comment]
oh i'm on d.py

**Comment by ZerioDev** [comment]
This source code uses `discord.js` 😓

**Comment by isigebengu-mikey** [comment]
Thanks for trying to help me, anyways!
